steps:
  - label: "Example Test"
    command: echo "Hello!"
  - label: "compile Tests"
    command: mvn clean compile
  - label: "Build app"
    command: mvn install
  - label: "create docker image"
    command: docker build -f Dockerfile -t docker-springboot-buildkite-image .

